# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5c95b13c344a57e29df37b9c15417008"
name = "api-noi-bo"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
